
var trees = [{
     "id": 1,
     "label": "V1.0",
     "parent_id": null,
     "url": null,
     "depth": 0,
     "child_num": 3,
     "description": "System Manager",
     "status":"开发中",
     "begin_date":"2017-06-21",
     "end_date":"2017-09-21",
     "children": [{
         "id": 2,
         "label": "V1.1",
         "parent_id": 1,
         "url": null,
         "depth": 1,
         "child_num": 5,
         "description": "Base Manager",
         "status":"开发中",
         "begin_date":"2017-06-21",
         "end_date":"2017-09-21",
         "expanded":true,
         "children": [{
             "id": 3,
             "label": "V1.2",
             "parent_id": 2,
             "url": "/menus",
             "depth": 2,
             "child_num": 0,
             "description": "menu manager",
             "status":"开发中",
             "begin_date":"2017-06-21",
             "end_date":"2017-09-21",
         }, {
             "id": 4,
             "label": "V1.3",
             "parent_id": 2,
             "url": "/roles",
             "depth": 2,
             "child_num": 0,
             "description": "Role Manager",
             "status":"开发中",
             "begin_date":"2017-06-21",
             "end_date":"2017-09-21",
         }, {
             "id": 5,
             "label": "V1.4",
             "parent_id": 2,
             "url": "/users",
             "depth": 2,
             "child_num": 0,
             "description": "User Manager",
             "status":"开发中",
             "begin_date":"2017-06-21",
             "end_date":"2017-09-21",
         }]
     }]
 }, {
     "id": 6,
     "label": "V1.5",
     "parent_id": null,
     "url": null,
     "depth": 0,
     "child_num": 2,
     "description": "Custom Manager",
     "status":"开发中",
     "begin_date":"2017-06-21",
     "end_date":"2017-09-21",
     "children": [{
         "id": 7,
         "label": "V1.6",
         "parent_id": 6,
         "url": "/customs",
         "depth": 1,
         "child_num": 0,
         "description": "CustomList",
         "status":"开发中",
         "begin_date":"2017-06-21",
         "end_date":"2017-09-21",
     }]
 }, {
     "id": 8,
     "label": "V1.7",
     "parent_id": null,
     "url": null,
     "depth": 0,
     "child_num": 1,
     "description": "Template Manager",
     "status":"开发中",
     "begin_date":"2017-06-21",
     "end_date":"2017-09-21",
     "children": [{
         "id": 9,
         "label": "V1.8",
         "parent_id": 8,
         "url": "/doc_templates",
         "depth": 1,
         "child_num": 0,
         "description": "Template Manager",
         "status":"开发中",
         "begin_date":"2017-06-21",
         "end_date":"2017-09-21",
     }]
 }, {
     "id": 10,
     "label": "V1.9",
     "parent_id": null,
     "url": null,
     "depth": 0,
     "child_num": 2,
     "description": "Bussiness Manager",
     "status":"开发中",
     "begin_date":"2017-06-21",
     "end_date":"2017-09-21",
     "expanded":false,
     "children": [{
         "id": 11,
         "label": "V2.0",
         "parent_id": 10,
         "url": null,
         "depth": 1,
         "child_num": 2,
         "description": "BussinessList",
         "status":"开发中",
         "begin_date":"2017-06-21",
         "end_date":"2017-09-21",
         "children": [{
             "id": 12,
             "label": "V2.1",
             "parent_id": 11,
             "url": "/currencies",
             "depth": 2,
             "child_num": 0,
             "description": "Currencies",
             "status":"开发中",
             "begin_date":"2017-06-21",
             "end_date":"2017-09-21",
         }, {
             "id": 13,
             "label": "V2.2",
             "parent_id": 11,
             "url": "/dealtypes",
             "depth": 2,
             "child_num": 0,
             "description": "Dealtypes",
             "status":"开发中",
             "begin_date":"2017-06-21",
             "end_date":"2017-09-21",
         }]
     }, {
         "id": 14,
         "label": "V2.3",
         "parent_id": 10,
         "url": null,
         "depth": 1,
         "child_num": 2,
         "description": "Products",
         "status":"开发中",
         "begin_date":"2017-06-21",
         "end_date":"2017-09-21",
         "children": [{
             "id": 15,
             "label": "V2.4",
             "parent_id": 14,
             "url": "/productTypes",
             "depth": 2,
             "child_num": 0,
             "description": "ProductTypes",
             "status":"准备开发",
             "begin_date":"2017-06-21",
             "end_date":"2017-09-21",
         }, {
             "id": 16,
             "label": "V2.5",
             "parent_id": 14,
             "url": "/products",
             "depth": 2,
             "child_num": 0,
             "description": "ProductList",
             "status":"开发完成",
             "begin_date":"2017-06-21",
             "end_date":"2017-09-21",
         }]
     }]
 }]
